### ISSUE TITLE
Include paths

### ISSUE THREAD

**Issue by pcj** [yugui/rules_ruby#7] opened 2018-09-22 18:57 UTC
In `helpers.bzl`, there is this code:

```python
includes = [
    "../%s/%s" % (ctx.workspace_name, inc) for inc in ctx.attr.includes
]
```

As a consequence, `ruby_library(includes = ['PATH]')` results in something like `ruby ... -I../com_github_foo_bar/PATH`.  Problem is, my runfiles tree does not look like this.  Instead, if the implementation looks like `"%s/%s" % (ctx.label.package, inc)` it works as expected.

@yugui What do you think?

**Comment by yugui** [comment] 2019-11-02 13:37
Thank you for reporting this and #8. I'm sorry for my very late reply.

Although I don't fully understand the reproducible case you had, I guess it was a combination of issues. (1) incomplete implementation of path construction in the binary wrapper; (2) runfiles structure change in Bazel.

I am closing this GH issue and #8  because I fixed the two issues in #11. But feel free to reopen it if it still reproduces in your environment.

**Closed as completed by yugui** 2019-11-02 13:37 UTC
